--- #YAML:1.0
name:                CGI-Session-Auth
version:             1.07
abstract:            Authenticated sessions for CGI scripts
license:             ~
author:              
    - Jochen Lillich <geewiz@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI:                           0
    CGI::Session:                  0
    Digest::MD5:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
